### ISSUE TITLE
Hello, would it be possible to change the downloadURL to the downloadable zip file ? This is the url that it needs to point to : https://github.com/nicolaserard/Spat-Revolution-Chataigne-Module/archive/refs/heads/main.zip This would allow putting the module in the official list and make it downloadable from Chataigne directly

### ISSUE THREAD

**Issue by benkuper** [l-r-r/Yamaha-CLQL-Chataigne-Module#1]
Hello,
would it be possible to change the downloadURL to the downloadable zip file ?
This is the url that it needs to point to : https://github.com/l-r-r/Yamaha-CLQL-Chataigne-Module/archive/refs/heads/master.zip
This would allow putting the module in the official list and make it downloadable from Chataigne directly.

PS : Thank you so much for being a sponsor, it means a lot !!

**Comment by l-r-r** [comment]
Hey !

Yes it's possible, and I'll look how to do that !

However, I'm not sure that's a good idea to put this module in the official Chataigne list for the moment. It's really a draft and not usable as is...

**Comment by benkuper** [comment]
ok !
let me know if you feel like putting it there at some point
